---
- name: Run Docker container
  hosts: 178.128.83.86
  become: yes
  vars:
    image_name: web-ui:latest
    container_name: webui_container
    container_port: 8080
    host_port: 8080
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        state: started

