---
- name: Run Docker container
  hosts: remote_host
  become: yes
  become_pass: "{{ lookup('env','ANSIBLE_BECOME_PASSWORD') }}"
  vars:
    image_name: webui:latest
    container_name: webui_container
    container_port: 8080
    host_port: 8080
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        state: started

