---
- name: Deploy Web UI container
  hosts: remote_host
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy WebUI container
      docker_container:
        name: webui
        image: deatend/webui:latest
        state: started
        recreate: yes
        ports:
          - "8080:8080"













- name: Run Docker container
  hosts: remote_host
  become: yes
  vars:
    ansible_become_pass: "{{ lookup('env','ANSIBLE_BECOME_PASSWORD') }}"
    image_name: webui:latest
    container_name: webui_container
    container_port: 8080
    host_port: 8080
  
