name: Deploy Docker to Digital Ocean 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: deatend/web-ui:latest

      - name: Deploy APIService
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ secrets.REMOTE_HOST }} ansible_ssh_port=${{ secrets.SSH_PORT }} ansible_ssh_user=${{ secrets.REMOTE_USER }} ansible_become_password=${{ secrets.SSH_BECOME_PASSWD }} ${{ PRIVATE_KEY_FILE }}
